version: '3.8'

services:
  blockchain-bitcoin:
    image: dobtc/bitcoin:28.0
    command:
      -rpcuser=${BITCOIN_NODE_RPC_USER}
      -rpcpassword=${BITCOIN_NODE_RPC_PASSWORD}
      -rpcallowip=${BITCOIN_NODE_RPC_ALLOW_IP:-0.0.0.0/0}
      -rpcbind=${BITCOIN_NODE_RPC_BIND:-0.0.0.0}
      -maxconnections=${BITCOIN_NODE_MAX_CONNECTIONS:-512}
      -printtoconsole
      -rpcworkqueue=4086
      -server=1
      -rest=1
      -txindex=1
      -rpcthreads=16
      -rpcworkqueue=128
      -dbcache=${BITCOIN_NODE_DB_CACHE:-40096}
      -par=${BITCOIN_NODE_PARALLEL_BLOCKS:-2}
    ports:
      - "8332:8332"
      - "8333:8333"
    volumes:
      - blockchain-bitcoin-data:/home/bitcoin/.bitcoin
    restart: unless-stopped

  money-flow-memgraph-live:
    container_name: money-flow-memgraph-live
    image: memgraph/memgraph-mage:1.22-memgraph-2.22
    ports:
      - "7687:7687"
      - "7444:7444"
    environment:
      - MEMGRAPH_USER=${MONEY_FLOW_MEMGRAPH_LIVE_USER:-mario}
      - MEMGRAPH_PASSWORD=${MONEY_FLOW_MEMGRAPH_LIVE_PASSWORD:-mariobros667}
    command: ["--storage-properties-on-edges=true", "--storage-enable-schema-metadata=true", "--storage-recovery-thread-count=60", "--storage-gc-cycle-sec=300", "--log-level=TRACE", "--also-log-to-stderr", "--storage-snapshot-on-exit=false", "--storage-snapshot-interval-sec=14400", "--storage-snapshot-retention-count=2", "--storage-wal-enabled=true", "--isolation-level=READ_COMMITTED", "--replication-restore-state-on-startup=true", "--query-execution-timeout-sec=0"]
    volumes:
      - money-flow-memgraph-live-data:/var/lib/memgraph
      - money-flow-memgraph-live-log:/var/log/memgraph
      - money-flow-memgraph-live-etc:/etc/memgraph
    restart: unless-stopped

  money-flow-memgraph-archive:
    container_name: money-flow-memgraph-archive
    image: memgraph/memgraph-mage:1.22-memgraph-2.22
    ports:
      - "7688:7687"
      - "7445:7444"
    environment:
      - MEMGRAPH_USER=${MONEY_FLOW_MEMGRAPH_ARCHIVE_USER:-mario}
      - MEMGRAPH_PASSWORD=${MONEY_FLOW_MEMGRAPH_ARCHIVE_PASSWORD:-mariobros667}
    command: ["--storage-mode=ON_DISK_TRANSACTIONAL",  "--storage-parallel-schema-recovery=true", "--storage-properties-on-edges=true", "--storage-recovery-thread-count=60",  "--log-level=TRACE", "--also-log-to-stderr",  "--query-execution-timeout-sec=0" ]
    volumes:
      - money-flow-memgraph-archive-data:/var/lib/memgraph
      - money-flow-memgraph-archive-log:/var/log/memgraph
      - money-flow-memgraph-archive-etc:/etc/memgraph
    restart: unless-stopped

  memgraph-lab:
    image: memgraph/lab:latest
    container_name: memgraph-lab
    ports:
      - "3000:3000"
    environment:
      - QUICK_CONNECT_MG_HOST=money-flow-memgraph-live
      - QUICK_CONNECT_MG_PORT=7687

  transaction-stream-clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"   # HTTP interface
      - "9000:9000"   # Native interface
      - "9009:9009"   # Interserver HTTP interface
    volumes:
      - transaction-stream-clickhouse-data:/var/lib/clickhouse
      - transaction-stream-clickhouse-logs:/var/log/clickhouse-server
      - "./init-clickhouse.sql:/docker-entrypoint-initdb.d/init-clickhouse.sql"
    environment:
      - CLICKHOUSE_DB=${TRANSACTION_STREAM_CLICKHOUSE_DB:-transaction_stream}
      - CLICKHOUSE_USER=${TRANSACTION_STREAM_CLICKHOUSE_USER:-default}
      - CLICKHOUSE_PASSWORD=${TRANSACTION_STREAM_CLICKHOUSE_PASSWORD:-changeit456$}
      - TRANSACTION_STREAM_CLICKHOUSE_QUERY_TIMEOUT=${TRANSACTION_STREAM_CLICKHOUSE_QUERY_TIMEOUT:-1800}
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    restart: unless-stopped

  clickhouse-ui:
    image: ghcr.io/caioricciuti/ch-ui:latest
    restart: always
    ports:
      - "${CH_UI_PORT:-5521}:5521"
    environment:
      - VITE_CLICKHOUSE_URL=http://${TRANSACTION_STREAM_CLICKHOUSE_USER:-default}:${TRANSACTION_STREAM_CLICKHOUSE_PASSWORD:-changeit456$}@localhost:8123/${TRANSACTION_STREAM_CLICKHOUSE_DB:-transaction_stream}
      - VITE_CLICKHOUSE_USER=${TRANSACTION_STREAM_CLICKHOUSE_USER:-default}
      - VITE_CLICKHOUSE_PASS=${TRANSACTION_STREAM_CLICKHOUSE_PASSWORD:-changeit456$}
    depends_on:
      - transaction-stream-clickhouse


  block-stream-postgres:
    image: postgres:16-alpine
    ports:
      - "5420:5432"
    volumes:
      - block-stream-postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${BLOCK_STREAM_POSTGRES_DB:-block_stream}
      - POSTGRES_USER=${BLOCK_STREAM_POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${BLOCK_STREAM_POSTGRES_PASSWORD:-changeit456$}

  block-stream-redpanda:
    container_name: block-stream-redpanda-0
    command:
      - redpanda
      - start
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      # Address the broker advertises to clients that connect to the Kafka API.
      # Use the internal addresses to connect to the Redpanda brokers'
      # from inside the same Docker network.
      # Use the external addresses to connect to the Redpanda brokers'
      # from outside the Docker network.
      - --advertise-kafka-addr internal://block-stream-redpanda-0:9092,external://localhost:19092
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:18082
      # Address the broker advertises to clients that connect to the HTTP Proxy.
      - --advertise-pandaproxy-addr internal://block-stream-redpanda-0:8082,external://localhost:18082
      - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:18081
      # Redpanda brokers use the RPC API to communicate with each other internally.
      - --rpc-addr block-stream-redpanda-0:33145
      - --advertise-rpc-addr block-stream-redpanda-0:33145
      # Mode dev-container uses well-known configuration properties for development in containers.
      - --mode dev-container
      # Tells Seastar (the framework Redpanda uses under the hood) to use 1 core on the system.
      - --smp 1
      - --default-log-level=info
    image: docker.redpanda.com/redpandadata/redpanda:v24.2.11
    volumes:
      - block-stream-redpanda-data:/var/lib/redpanda/data
    ports:
      - 18081:18081
      - 18082:18082
      - 19092:19092
      - 19644:9644

  redpanda-console:
    container_name: redpanda-console
    image: docker.redpanda.com/redpandadata/console:v2.7.2
    entrypoint: /bin/sh
    command: -c 'echo "$$CONSOLE_CONFIG_FILE" > /tmp/config.yml; /app/console'
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
          kafka:
            brokers: ["block-stream-redpanda:9092"]
            schemaRegistry:
              enabled: true
              urls: ["http://block-stream-redpanda:8081"]
          redpanda:
            adminApi:
              enabled: true
              urls: ["http://block-stream-redpanda:9644"]
    ports:
      - 8080:8080
    depends_on:
      - block-stream-redpanda

volumes:
  blockchain-bitcoin-data:
    name: blockchain-bitcoin-data

  money-flow-memgraph-live-data:
    name: money-flow-memgraph-live-data
  money-flow-memgraph-live-log:
    name: money-flow-memgraph-live-log
  money-flow-memgraph-live-etc:
    name: money-flow-memgraph-live-etc

  money-flow-memgraph-archive-data:
    name: money-flow-memgraph-archive-data
  money-flow-memgraph-archive-log:
    name: money-flow-memgraph-archive-log
  money-flow-memgraph-archive-etc:
    name: money-flow-memgraph-archive-etc

  transaction-stream-clickhouse-data:
    name: transaction-stream-clickhouse-data
  transaction-stream-clickhouse-logs:
    name: transaction-stream-clickhouse-logs

  block-stream-postgres-data:
    name: block-stream-postgres-data

  block-stream-redpanda-data:
    name: block-stream-redpanda-data